language: go
go:
  - 1.1
  - 1.2
  - tip
before_install:
  - sudo apt-get install libgeoip-dev bzr
install:
  - mkdir -p $TRAVIS_BUILD_DIR/db
  - curl -s http://geodns.bitnames.com/geoip/GeoLiteCity.dat.gz | gzip -cd > $TRAVIS_BUILD_DIR/db/GeoIPCity.dat
  - curl -s http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNum.dat.gz | gzip -cd > $TRAVIS_BUILD_DIR/db/GeoIPASNum.dat
  - go get github.com/abh/dns
  - go get github.com/abh/geoip
  - go get gopkg.in/check.v1
  - go get -v
  - go build -v
  - go install

script:
  - cd $TRAVIS_BUILD_DIR && go test -gocheck.v
  - go test -gocheck.v -gocheck.b -gocheck.btime=2s
